### ISSUE TITLE
Bug report: twice the same token

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#69] opened 2020-09-25 12:19 UTC

**Comment by c3rnst** [comment] 2020-09-25 12:20
<img width="255" alt="Screenshot 2020-09-25 at 10 22 40" src="https://user-images.githubusercontent.com/34367524/94266308-3f18d700-ff3a-11ea-861e-c672c3c321a3.png">

see OWL on this one.

**Comment by alfetopito** [comment] 2020-10-05 23:27
Do you still see that?

**Comment by alfetopito** [comment] 2020-10-05 23:28
Oops, closed by accident

**Comment by c3rnst** [comment] 2020-10-06 08:47
No, I don't see it any longer.

**Closed** 2020-10-06 15:43 UTC
Labels: bug

**Comment by elena-zh** [comment] 2020-10-07 08:11
Verified. The issue is not reproducible for me as well.
